/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseEmptyState: typeof import('./src/components/BaseEmptyState.vue')['default']
    BaseErrorState: typeof import('./src/components/BaseErrorState.vue')['default']
    BaseLoadingState: typeof import('./src/components/BaseLoadingState.vue')['default']
    BaseStateContainer: typeof import('./src/components/BaseStateContainer.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConnectWalletPrompt: typeof import('./src/components/ConnectWalletPrompt.vue')['default']
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Languages: typeof import('./src/components/Languages.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    WalletGate: typeof import('./src/components/WalletGate.vue')['default']
    WrongNetworkBanner: typeof import('./src/components/WrongNetworkBanner.vue')['default']
    WrongTronNetworkBanner: typeof import('./src/components/WrongTronNetworkBanner.vue')['default']
  }
}
